### ISSUE TITLE
"warning: parsing failures"

### ISSUE THREAD

**Issue by Valentin-Bio-zz** [arendsee/rhmmer#2]
Hello I just want to read my hmmscan tblout output, When I read the file using:
`SLF2_ARG_hmmsearch <- rhmmer::read_tblout("SLF2_tblout.scan")`

I got the follwing message:

> Warning: 572 parsing failures.
> row         col           expected actual         file
>   1 description delimiter or quote        literal data
>   1 description delimiter or quote      S literal data
>   1 description delimiter or quote        literal data
>   1 description delimiter or quote      t literal data
>   1 description delimiter or quote        literal data
> ... ........... .................. ...... ............

> See problems(...) for more details.

the "SLF2_ARG_hmmsearch" variable results in 12 observations which are reallly lowin comparison of what is displayed when looking the file in bash.

**Comment by arendsee** [comment]
Hi @Valentin-Bio, could you post a small example of a file that fails?

**Comment by Valentin-Bio-zz** [comment]
https://www.dropbox.com/s/dgnd930816kvwmm/SLF2_tblout.scan?dl=0 

the above one is one of the files that have that problem, I have 30 files of the same type and 29 of them returns the same problem, however this file works:
https://www.dropbox.com/s/j0iqql8k2l4c2pa/SLF1_tblout.scan?dl=0

Thanks for you fast answer :)

**Comment by Valentin-Bio-zz** [comment]
when typing `problems(SLF2_tblout.scan)` I got the following:

> > problems(SLF2_ARG_hmmsearch)
> [1] row      col      expected actual  
> <0 rows> (or 0-length row.names)

**Comment by arendsee** [comment]
Thanks for the files, I'll look into it this evening and see if I can figure out what is going on. Do you mind if I use a subset of your data in a test case?

**Comment by Valentin-Bio-zz** [comment]
> Thanks for the files, I'll look into it this evening and see if I can figure out what is going on. Do you mind if I use a subset of your data in a test case?

no problem 👍🏼

**Comment by arendsee** [comment]
@Valentin-Bio It should work now. The parser was breaking on the quoted strings inside the description. Now the description can contain any string. I haven't pushed this to CRAN yet, so you'll need to reinstall through github.

**Comment by Valentin-Bio-zz** [comment]
Thanks so much for this! I appreciate it a lot. :)
